spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false

clinica:
  jwt:
    secret: xKT/6YEXF~lw;QpIqc<|A(]FV2{Ei([I#sAa_IiiFZcW)=|+7&7X5XpWs|_)67"
    expiration: 10800000